export const COMMON_URL = {
  getCategoryInfo: "/api/db/getCategory",
  getBookList: "/api/db/getBookList",
  getBookListWithWriter: "/api/db/getBookListWithWriter",
  getBookListForIds: "/api/db/getBookListForIds",
  getBookListForWriter: "/api/db/getBookListForWriter",
  getBookInfo: "/api/db/getBookInfo",
  getNewBookList: "/api/db/getNewBookList",
  getBookSeries: "/api/db/getBookSeries",
  getWriterInfo: "/api/db/getWriterInfo",
  getWriterListForIds: "/api/db/getWriterListForIds",
  getTranslatorInfo: "/api/db/getTranslatorInfo",
  getArtistInfo: "/api/db/getArtistInfo",
  getPublisherInfo: "/api/db/getPublisherInfo",
  getEventList: "/api/db/getEventList",
  getEventInfo: "/api/db/getEventInfo",
};
